#ifndef _ALTERA_ACCELERATOR_0_H_
#define _ALTERA_ACCELERATOR_0_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'base_hps' in
 * file 'base_hps.sopcinfo'.
 */

/*
 * This file contains macros for module 'accelerator_0' and devices
 * connected to the following master:
 *   avalon_master
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */


#endif /* _ALTERA_ACCELERATOR_0_H_ */
